"use client"

import * as React from "react"
import { Check, Download, ExternalLink, Info, Keyboard, Layers, Plus, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Slider } from "@/components/ui/slider"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"

const presets = [16, 32, 64, 128] as const
type Preset = (typeof presets)[number] | "custom"

export interface NewProjectOptions { name: string; width: number; height: number; transparent: boolean; background: string }
export interface NewProjectDialogProps { open: boolean; onOpenChange: (open: boolean) => void; onCreate: (options: NewProjectOptions) => void; initialName?: string }

export function NewProjectDialog({ open, onOpenChange, onCreate, initialName = "Untitled sprite" }: NewProjectDialogProps) {
  const [name, setName] = React.useState(initialName)
  const [preset, setPreset] = React.useState<Preset>(32)
  const [width, setWidth] = React.useState(32)
  const [height, setHeight] = React.useState(32)
  const [transparent, setTransparent] = React.useState(true)
  const [background, setBackground] = React.useState("#171922")
  const valid = name.trim().length > 0 && width >= 1 && width <= 256 && height >= 1 && height <= 256
  const choose = (value: Preset) => { setPreset(value); if (value !== "custom") { setWidth(value); setHeight(value) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#11131b] text-white sm:max-w-[500px]">
    <DialogHeader><DialogTitle className="flex items-center gap-2 font-mono"><Plus className="size-4 text-violet-400" />New project</DialogTitle><DialogDescription className="text-slate-400">Set up a canvas for your next pixel creation.</DialogDescription></DialogHeader>
    <div className="space-y-5">
      <div className="space-y-2"><Label htmlFor="project-name">Project name</Label><Input id="project-name" value={name} onChange={e => setName(e.target.value)} className="border-white/10 bg-white/5" autoFocus /></div>
      <div className="space-y-2"><Label>Canvas size</Label><div className="grid grid-cols-4 gap-2">{presets.map(size => <Button key={size} type="button" variant="outline" onClick={() => choose(size)} className={cn("border-white/10 bg-white/5 font-mono", preset === size && "border-violet-400 bg-violet-500/20 text-violet-200")}>{size}×{size}</Button>)}<Button type="button" variant="outline" onClick={() => choose("custom")} className={cn("border-white/10 bg-white/5", preset === "custom" && "border-violet-400 bg-violet-500/20")}>Custom</Button></div></div>
      <div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label htmlFor="canvas-width">Width</Label><Input id="canvas-width" type="number" min={1} max={256} value={width} onChange={e => { setPreset("custom"); setWidth(Number(e.target.value)) }} /></div><div className="space-y-2"><Label htmlFor="canvas-height">Height</Label><Input id="canvas-height" type="number" min={1} max={256} value={height} onChange={e => { setPreset("custom"); setHeight(Number(e.target.value)) }} /></div></div>
      <div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[.03] p-3"><div><Label htmlFor="transparent">Transparent background</Label><p className="text-xs text-slate-500">Keep the canvas alpha channel</p></div><Switch id="transparent" checked={transparent} onCheckedChange={setTransparent} /></div>
      {!transparent && <div className="space-y-2"><Label htmlFor="background">Background color</Label><div className="flex gap-2"><Input id="background" type="color" value={background} onChange={e => setBackground(e.target.value)} className="h-10 w-14 p-1" /><Input aria-label="Background hex" value={background} onChange={e => setBackground(e.target.value)} className="font-mono" /></div></div>}
    </div>
    <DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!valid} onClick={() => onCreate({ name: name.trim(), width, height, transparent, background })}>Create canvas</Button></DialogFooter>
  </DialogContent></Dialog>
}

export type ExportFormat = "png" | "gif"
export interface ExportOptions { format: ExportFormat; scale: number; columns: number; spacing: number; loop: boolean }
export interface ExportDialogProps { open: boolean; onOpenChange: (open: boolean) => void; frameCount?: number; projectName?: string; onExport: (options: ExportOptions) => void }
export function ExportDialog({ open, onOpenChange, frameCount = 1, projectName = "sprite", onExport }: ExportDialogProps) {
  const [format, setFormat] = React.useState<ExportFormat>("png"); const [scale, setScale] = React.useState(1); const [columns, setColumns] = React.useState(Math.max(1, Math.min(frameCount, 8))); const [spacing, setSpacing] = React.useState(0); const [loop, setLoop] = React.useState(true)
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#11131b] text-white sm:max-w-[520px]"><DialogHeader><DialogTitle className="flex items-center gap-2 font-mono"><Download className="size-4 text-violet-400" />Export {projectName}</DialogTitle><DialogDescription className="text-slate-400">Choose a format and configure the output.</DialogDescription></DialogHeader>
    <Tabs value={format} onValueChange={v => setFormat(v as ExportFormat)}><TabsList className="grid w-full grid-cols-2 bg-white/5"><TabsTrigger value="png">PNG sprite sheet</TabsTrigger><TabsTrigger value="gif">Animated GIF</TabsTrigger></TabsList><TabsContent value="png" className="space-y-5 pt-4"><ExportSlider label="Scale" value={scale} min={1} max={8} step={1} onChange={setScale} suffix="×" /><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label htmlFor="columns">Columns</Label><Input id="columns" type="number" min={1} max={frameCount} value={columns} onChange={e => setColumns(Math.max(1, Number(e.target.value)))} /></div><div className="space-y-2"><Label htmlFor="spacing">Frame spacing</Label><Input id="spacing" type="number" min={0} max={64} value={spacing} onChange={e => setSpacing(Math.max(0, Number(e.target.value)))} /></div></div><p className="text-xs text-slate-500">{frameCount} frame{frameCount === 1 ? "" : "s"} · {columns} column{columns === 1 ? "" : "s"}</p></TabsContent><TabsContent value="gif" className="space-y-5 pt-4"><ExportSlider label="Scale" value={scale} min={1} max={8} step={1} onChange={setScale} suffix="×" /><div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[.03] p-3"><div><Label htmlFor="loop">Loop animation</Label><p className="text-xs text-slate-500">Repeat until the viewer closes it</p></div><Switch id="loop" checked={loop} onCheckedChange={setLoop} /></div></TabsContent></Tabs><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => onExport({ format, scale, columns, spacing, loop })}><Download className="size-4" />Export {format.toUpperCase()}</Button></DialogFooter></DialogContent></Dialog>
}
function ExportSlider({ label, value, min, max, step, suffix, onChange }: { label: string; value: number; min: number; max: number; step: number; suffix?: string; onChange: (value: number) => void }) { return <div className="space-y-3"><div className="flex justify-between"><Label>{label}</Label><span className="font-mono text-sm text-violet-300">{value}{suffix}</span></div><Slider value={[value]} min={min} max={max} step={step} onValueChange={v => onChange(v[0] ?? value)} aria-label={label} /></div> }

export interface ShortcutsDialogProps { open: boolean; onOpenChange: (open: boolean) => void; shortcuts?: Array<{ keys: string[]; label: string; category?: string }> }
const defaultShortcuts = [{ keys: ["B"], label: "Brush" }, { keys: ["E"], label: "Eraser" }, { keys: ["G"], label: "Fill" }, { keys: ["I"], label: "Eyedropper" }, { keys: ["⌘", "Z"], label: "Undo" }, { keys: ["⌘", "⇧", "Z"], label: "Redo" }, { keys: ["Space"], label: "Pan canvas" }, { keys: ["[", "]"], label: "Change brush size" }]
export function ShortcutsDialog({ open, onOpenChange, shortcuts = defaultShortcuts }: ShortcutsDialogProps) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#11131b] text-white sm:max-w-[520px]"><DialogHeader><DialogTitle className="flex items-center gap-2 font-mono"><Keyboard className="size-4 text-violet-400" />Keyboard shortcuts</DialogTitle><DialogDescription className="text-slate-400">Speed up your workflow with these commands.</DialogDescription></DialogHeader><div className="grid grid-cols-1 gap-1 sm:grid-cols-2">{shortcuts.map((item, i) => <div key={`${item.label}-${i}`} className="flex items-center justify-between rounded-md px-3 py-2.5 hover:bg-white/5"><span className="text-sm">{item.label}</span><span className="flex gap-1">{item.keys.map(key => <kbd key={key} className="rounded border border-white/15 bg-white/5 px-1.5 py-0.5 font-mono text-xs text-slate-300">{key}</kbd>)}</span></div>)}</div></DialogContent></Dialog> }

export interface WebMCPTool { name: string; description: string; enabled?: boolean }
export interface WebMCPDialogProps { open: boolean; onOpenChange: (open: boolean) => void; available?: boolean; tools?: WebMCPTool[]; onRefresh?: () => void }
export function WebMCPDialog({ open, onOpenChange, available = false, tools = [], onRefresh }: WebMCPDialogProps) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-white/10 bg-[#11131b] text-white sm:max-w-[560px]"><DialogHeader><DialogTitle className="flex items-center gap-2 font-mono"><Sparkles className="size-4 text-violet-400" />WebMCP connection</DialogTitle><DialogDescription className="text-slate-400">Connect compatible web agents to automate PixelForge actions.</DialogDescription></DialogHeader><div className="space-y-4"><div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[.03] p-4"><div className="flex items-center gap-3"><span className={cn("size-2.5 rounded-full", available ? "bg-emerald-400" : "bg-amber-400")} /><div><p className="font-medium">{available ? "WebMCP is available" : "Waiting for a WebMCP host"}</p><p className="text-xs text-slate-500">{available ? "This editor can receive tool calls." : "Open this page in a compatible host to enable automation."}</p></div></div><Badge variant="outline" className="border-white/15">{available ? "Connected" : "Not connected"}</Badge></div><div className="rounded-lg border border-white/10 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-medium"><Layers className="size-4 text-violet-300" />Available tools <span className="text-xs text-slate-500">({tools.length})</span></div>{tools.length ? <div className="space-y-2">{tools.map(tool => <div key={tool.name} className="flex items-center gap-2 text-sm"><Check className="size-3.5 text-emerald-400" /><span className="font-mono text-xs">{tool.name}</span><span className="truncate text-xs text-slate-500">{tool.description}</span></div>)}</div> : <p className="text-xs text-slate-500">Tools will appear here when a host connects.</p>}</div><div className="flex gap-2 rounded-lg bg-violet-500/10 p-3 text-xs text-violet-200"><Info className="mt-0.5 size-4 shrink-0" /><p>WebMCP lets an external agent request editor operations through explicit, permissioned tools. Your pixels stay in this browser unless you export them.</p></div></div><DialogFooter><Button variant="ghost" onClick={() => onOpenChange(false)}>Close</Button>{onRefresh && <Button variant="outline" onClick={onRefresh}>Refresh status</Button>}<Button variant="outline" asChild><a href="https://webmcp.dev" target="_blank" rel="noreferrer">WebMCP docs <ExternalLink className="size-3.5" /></a></Button></DialogFooter></DialogContent></Dialog> }
