/** Browser-only, dependency-free exporters for PixelForge projects. */
import type { Project, Frame, Layer } from './types'

export type SpriteSheetLayout = 'horizontal' | 'vertical' | 'grid'
export interface SpriteSheetOptions { layout?: SpriteSheetLayout; columns?: number; gap?: number; scale?: number }
export interface GifOptions { delay?: number | number[]; loop?: number; scale?: number }

const safeName = (name: string) => (name || 'pixelforge').replace(/[^a-z0-9._-]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 100) || 'pixelforge'
export function sanitizeFilename(name: string, fallback = 'pixelforge'): string { return safeName(name) || fallback }
export function downloadBlob(blob: Blob, filename: string): void { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = sanitizeFilename(filename); a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000) }

type Px = [number, number, number, number]
const parse = (s: string): Px => { if (!s || s === 'transparent') return [0, 0, 0, 0]; const h = s.replace('#', ''); const n = h.length === 3 ? h.split('').map(x => x + x).join('') : h; return [parseInt(n.slice(0, 2), 16) || 0, parseInt(n.slice(2, 4), 16) || 0, parseInt(n.slice(4, 6), 16) || 0, n.length >= 8 ? parseInt(n.slice(6, 8), 16) : 255] }
const layerPixels = (l: Layer): string[] => { const p = (l as unknown as { pixels?: string[] | string }).pixels; return Array.isArray(p) ? p : typeof p === 'string' ? [...p] : [] }
export function compositeFrame(frame: Frame, width: number, height: number): Uint8ClampedArray {
  const out = new Uint8ClampedArray(width * height * 4); const layers = ((frame as unknown as { layers?: Layer[] }).layers || []).filter(l => (l as unknown as { visible?: boolean }).visible !== false)
  for (const l of layers) { const px = layerPixels(l), opacity = (l as unknown as { opacity?: number }).opacity ?? 1; for (let i = 0; i < width * height; i++) { const s = parse(px[i] || ''); const a = s[3] / 255 * opacity; if (!a) continue; const o = i * 4, da = out[o + 3] / 255, oa = a + da * (1 - a); out[o] = (s[0] * a + out[o] * da * (1 - a)) / oa; out[o + 1] = (s[1] * a + out[o + 1] * da * (1 - a)) / oa; out[o + 2] = (s[2] * a + out[o + 2] * da * (1 - a)) / oa; out[o + 3] = oa * 255 } } return out
}
const crc = (d: Uint8Array) => { let c = 0xffffffff; for (const x of d) { c ^= x; for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (c & 1 ? 0xedb88320 : 0) } return (c ^ 0xffffffff) >>> 0 }
const u32 = (n: number) => new Uint8Array([(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255])
async function deflate(data: Uint8Array): Promise<Uint8Array> { if ('CompressionStream' in globalThis) { const w = new (globalThis as unknown as { CompressionStream: new (x: string) => CompressionStream }).CompressionStream('deflate'); const writer = w.writable.getWriter(); writer.write(data); writer.close(); return new Uint8Array(await new Response(w.readable).arrayBuffer()) } const z = new Uint8Array(data.length + Math.ceil(data.length / 65535) * 5 + 6); z[0] = 0x78; z[1] = 1; let p = 2, off = 0; while (off < data.length) { const n = Math.min(65535, data.length - off); z[p++] = off + n >= data.length ? 1 : 0; z[p++] = n & 255; z[p++] = n >>> 8; z[p++] = (~n) & 255; z[p++] = (~n) >>> 8; z.set(data.subarray(off, off + n), p); p += n; off += n } z.set(u32(adler(data)), p); return z.subarray(0, p + 4) }
const adler = (d: Uint8Array) => { let a = 1, b = 0; for (const x of d) { a = (a + x) % 65521; b = (b + a) % 65521 } return (b << 16) | a }
export async function rgbaToPng(rgba: Uint8ClampedArray, width: number, height: number, scale = 1): Promise<Blob> { const raw = new Uint8Array(height * (width * 4 + 1)); for (let y = 0; y < height; y++) { raw[y * (width * 4 + 1)] = 0; raw.set(rgba.subarray(y * width * 4, (y + 1) * width * 4), y * (width * 4 + 1) + 1) } const ih = new Uint8Array(13); ih.set(u32(width), 0); ih.set(u32(height), 4); ih[8] = 8; ih[9] = 6; const chunk = (t: string, d: Uint8Array) => { const tb = new TextEncoder().encode(t), all = new Uint8Array(tb.length + d.length); all.set(tb); all.set(d, tb.length); return new Uint8Array([...u32(d.length), ...all, ...u32(crc(all))]) }; const body = new Uint8Array([...new Uint8Array([137,80,78,71,13,10,26,10]), ...chunk('IHDR', ih), ...chunk('IDAT', await deflate(raw)), ...chunk('IEND', new Uint8Array())]); if (scale === 1) return new Blob([body], { type: 'image/png' }); const c = document.createElement('canvas'); c.width = width * scale; c.height = height * scale; const x = c.getContext('2d')!; x.imageSmoothingEnabled = false; const im = new ImageData(rgba, width, height); x.putImageData(im, 0, 0); x.drawImage(c, 0, 0); return new Promise(r => c.toBlob(b => r(b!), 'image/png')) }
export async function exportFramePng(frame: Frame, width: number, height: number, scale = 1): Promise<Blob> { return rgbaToPng(compositeFrame(frame, width, height), width, height, scale) }
export async function exportProjectJson(project: Project): Promise<Blob> { return new Blob([JSON.stringify(project, null, 2)], { type: 'application/json' }) }
export async function exportFrameSequence(project: Project, width: number, height: number, scale = 1): Promise<Blob[]> { return Promise.all((project as unknown as { frames: Frame[] }).frames.map(f => exportFramePng(f, width, height, scale))) }
/** Animated GIF89a export using a global 3-3-2 palette and standards-compliant LZW blocks. */
export async function exportAnimatedGif(frames: Frame[], width: number, height: number, options: GifOptions = {}): Promise<Blob> {
  const bytes: number[] = [...new TextEncoder().encode('GIF89a'), width, 0, height, 0, 0xf7, 0, 0];
  for (let i = 0; i < 256; i++) bytes.push(((i >> 5) & 7) * 36, ((i >> 2) & 7) * 36, (i & 3) * 85);
  bytes.push(0x21, 0xff, 11, ...new TextEncoder().encode('NETSCAPE2.0'), 3, 1, options.loop ?? 0, (options.loop ?? 0) >> 8, 0);
  for (let fi = 0; fi < frames.length; fi++) { const rgba = compositeFrame(frames[fi], width, height), idx: number[] = []; for (let i = 0; i < width * height; i++) { const o = i * 4; idx.push(rgba[o + 3] < 128 ? 0 : (rgba[o] & 0xe0) | ((rgba[o + 1] >> 3) & 0x1c) | (rgba[o + 2] >> 6)) } const d = Array.isArray(options.delay) ? options.delay[fi] || 0 : options.delay || 10; bytes.push(0x21, 0xf9, 4, 1, d & 255, d >> 8, 0, 0, 0x2c, 0, 0, 0, 0, width, 0, height, 0, 0, 8); const packed = lzwEncode(idx); for (let p = 0; p < packed.length; p += 255) { const n = Math.min(255, packed.length - p); bytes.push(n, ...packed.slice(p, p + n)) } bytes.push(0) } bytes.push(0x3b); return new Blob([new Uint8Array(bytes)], { type: 'image/gif' })
}
function lzwEncode(input: number[]): number[] { const clear = 256, end = 257, dict = new Map<string, number>(); for (let i = 0; i < 256; i++) dict.set(String.fromCharCode(i), i); let next = 258, codeSize = 9, bits = 0, acc = 0, out: number[] = []; const put = (n: number) => { acc |= n << bits; bits += codeSize; while (bits >= 8) { out.push(acc & 255); acc >>>= 8; bits -= 8 } }; put(clear); let s = ''; for (const n of input) { const c = s + String.fromCharCode(n); if (dict.has(c)) s = c; else { put(dict.get(s)!); if (next < 4096) { dict.set(c, next++); if (next === (1 << codeSize) && codeSize < 12) codeSize++ } s = String.fromCharCode(n) } } if (s) put(dict.get(s)!); put(end); if (bits) out.push(acc); return out }
