import { Anchor, Cel, Frame, Layer, Palette, Pixel, PixelProject, Pixels } from './types';
let seq = 0; const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${(++seq).toString(36)}`;
export const blankPixels = (w: number, h: number): Pixels => Array(w*h).fill('');
export const pixelIndex = (x:number,y:number,w:number) => y*w+x;
export function createProject(width=32,height=32,name='Untitled'): PixelProject { if(width<1||height<1) throw new Error('Canvas dimensions must be positive'); const l:Layer={id:id('layer'),name:'Layer 1',visible:true,locked:false,opacity:1,frameIds:[]}; const f:Frame={id:id('frame'),index:0,duration:100}; const c:Cel={id:id('cel'),frameId:f.id,layerId:l.id,pixels:blankPixels(width,height),duration:100}; l.frameIds=[c.id]; return {version:1,id:id('project'),name,width,height,layers:[l],frames:[f],cels:{[c.id]:c},palettes:[],activeLayerId:l.id,activeFrameId:f.id,tool:{tool:'pencil',color:'#000000',size:1,fill:false},onionSkin:{enabled:false,previous:1,next:1,opacity:.25},symmetry:{enabled:false,x:false,y:false,centerX:width/2,centerY:height/2},selection:null}; }
export const celFor = (p:PixelProject,layerId:string,frameId:string) => Object.values(p.cels).find(c=>c.layerId===layerId&&c.frameId===frameId);
export function ensureCel(p:PixelProject,layerId:string,frameId:string): Cel { const c=celFor(p,layerId,frameId); if(!c) throw new Error('Cel not found'); return c; }
export function resizePixels(src:Pixels,oldW:number,oldH:number,w:number,h:number,anchor:Anchor='top-left'):Pixels { const out=blankPixels(w,h); const dx=anchor.includes('right')?w-oldW:anchor.includes('left')?0:Math.floor((w-oldW)/2); const dy=anchor.includes('bottom')?h-oldH:anchor.includes('top')?0:Math.floor((h-oldH)/2); for(let y=0;y<oldH;y++)for(let x=0;x<oldW;x++){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<w&&ny<h)out[pixelIndex(nx,ny,w)]=src[pixelIndex(x,y,oldW)];} return out; }
export function validateProject(p:unknown): p is PixelProject { const x=p as PixelProject; return !!x&&x.version===1&&Number.isInteger(x.width)&&x.width>0&&Number.isInteger(x.height)&&Array.isArray(x.layers)&&Array.isArray(x.frames)&&!!x.cels; }
export const serializeProject=(p:PixelProject)=>JSON.stringify(p);
export function deserializeProject(raw:string):PixelProject { const p=JSON.parse(raw); if(!validateProject(p)) throw new Error('Invalid PixelForge project'); return p; }
